ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.evandhardspace.movie.server.HttpKt.configureHttp
      - com.evandhardspace.movie.server.SerializationKt.configureSerialization
      - com.evandhardspace.movie.server.SecurityKt.configureSecurity
      - com.evandhardspace.movie.server.DIKt.configureDependencyInjection
      - com.evandhardspace.movie.server.ExposedKt.configureExposed
      - com.evandhardspace.movie.server.RoutingKt.configureRouting
